<?php
include ("header.php");
?>

<section id="main">
	<h2>Cars Gallery</h2><br>
	<div id="products" class="row">
		<!-- product-card generated by js -->
	</div> 
</section>
</div>
<script src="readxml.js"></script>
<script src="updateproduct.js"></script>

<?php
include ("footer.php");
?>
